# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GangwonDoranDoran' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GangwonDoranDoran
       pod 'GoogleSignIn'

  target 'GangwonDoranDoranTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GangwonDoranDoranUITests' do
    # Pods for testing
  end

end
